/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-25 13:43:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.project_005fdetail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.project.model.vo.*;
import java.util.Date;
import java.util.Date;
import com.kh.attachment.model.vo.*;
import java.text.SimpleDateFormat;
import com.kh.member.model.vo.Member;
import com.kh.attachment.model.vo.ProfileAttachment;

public final class projectDetailReview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/project_detail/../common/menubar.jsp", Long.valueOf(1629435486986L));
    _jspx_dependants.put("/views/project_detail/../common/footer.jsp", Long.valueOf(1629160704073L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629163645819L));
    _jspx_dependants.put("jar:file:/C:/Users/User/git/Fun-ding/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.kh.project.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kh.attachment.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.kh.attachment.model.vo.ProfileAttachment");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fgroupingUsed_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fgroupingUsed_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fgroupingUsed_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

Project project = (Project)request.getAttribute("project");
ProjectCat projectCat = (ProjectCat)request.getAttribute("projectCat");
ArrayList<ProjectAttachment> prjAttList = (ArrayList<ProjectAttachment>)request.getAttribute("prjAttList");
int num= project.getPrjNo();
Date date = new Date();
SimpleDateFormat sdFormat = new SimpleDateFormat("yy/MM/dd");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>프로젝트 상세페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/projectDetail.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");

 	Member loginUser = (Member)session.getAttribute("loginUser");
 	ProfileAttachment at = (ProfileAttachment)session.getAttribute("at");
 	String message = (String)session.getAttribute("msg");
 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Fund-ing</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script> \r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	min-width: 1200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navWrap {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 50px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navWrap>.nav {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navWrap>.logo {\r\n");
      out.write("	width: 700px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: rgb(31, 80, 126);\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	display: table-cell;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	font-family: 'Black Han Sans';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: 160px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	display: table-cell;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	font-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu:hover {\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: black 1px solid;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("	background-color: rgb(31, 80, 126);\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userInfo {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:visited {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("	color: rgb(31, 80, 126);;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("	border-radius: 70%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    var msg = \"");
      out.print(message);
      out.write("\";\r\n");
      out.write("    \r\n");
      out.write("    if(msg != \"null\"){\r\n");
      out.write("       alert(msg);	\r\n");
      out.write("       \r\n");
      out.write("       ");
session.removeAttribute("msg");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write(" 	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
 if(loginUser == null){ 
      out.write("\r\n");
      out.write("	<div class=\"navWrap\">\r\n");
      out.write("		<span class=\"nav\">\r\n");
      out.write("			<div class=\"logo\">fund-ing</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goMain();\">홈</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProject();\">프로젝트 둘러보기</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProjectUp();\">프로젝트 올리기</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goCommunity();\">커뮤니티</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goConsumer();\">고객지원</div>\r\n");
      out.write("\r\n");
      out.write("		</span> \r\n");
      out.write("		<span class=\"info\">\r\n");
      out.write("			<button class=\"btn\" onclick=\"login()\">로그인</button>&nbsp;\r\n");
      out.write("			<button class=\"btn\" onclick=\"enroll()\">회원가입</button>\r\n");
      out.write("		</span>\r\n");
      out.write("		<hr style=\"height: 1px; background-color: black;\">\r\n");
      out.write("	</div>\r\n");
      out.write("	");
 }else{
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		");
if(loginUser.getMemNo() == 100) { 
      out.write(" <!-- 관리자 로그인상태라면 -->\r\n");
      out.write("		<div class=\"navWrap\">\r\n");
      out.write("		<span class=\"nav\">\r\n");
      out.write("			<div class=\"logo\">fund-ing</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goMain();\">홈</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProject();\">프로젝트 둘러보기</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProjectUp();\">프로젝트 올리기</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goCommunity();\">커뮤니티</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goConsumer();\">고객지원</div>\r\n");
      out.write("\r\n");
      out.write("		</span> \r\n");
      out.write("		\r\n");
      out.write("		<img id=\"profile\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/default.PNG\" style=\"width:50px; height:50px\"> \r\n");
      out.write("		\r\n");
      out.write("		<span class=\"userInfo\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/memberList.bo\" style=\"font-size:15px; font-weight:bold;\">회원 리스트</a><br>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\" style=\"font-size:10px; font-weight:bold; color:red;\"> 로그아웃</a>\r\n");
      out.write("        </span>\r\n");
      out.write("		<hr style=\"height: 1px; background-color: black;\">\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		");
} else {
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"navWrap\">\r\n");
      out.write("		<span class=\"nav\">\r\n");
      out.write("			<div class=\"logo\">fund-ing</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goMain();\">홈</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProject();\">프로젝트 둘러보기</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProjectUp();\">프로젝트 올리기</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goCommunity();\">커뮤니티</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goConsumer();\">고객지원</div>\r\n");
      out.write("\r\n");
      out.write("		</span> \r\n");
      out.write("		\r\n");
      out.write("		");
if(at == null){ 
      out.write("\r\n");
      out.write("		<img id=\"profile\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/default.PNG\" style=\"width:50px; height:50px\"> \r\n");
      out.write("		");
} else { 
      out.write("\r\n");
      out.write("		<img id=\"profile\"  src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/upfiles_profile/");
      out.print( at.getChangeName());
      out.write("\" style=\"width:50px; height:50px\"> \r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		 \r\n");
      out.write("		<span class=\"userInfo\">\r\n");
      out.write("            <a href=\"\" style=\"font-size:15px; font-weight:bold;\">");
      out.print( loginUser.getMemName() );
      out.write("</a><br>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\" style=\"font-size:10px; font-weight:bold; color:red;\"> 로그아웃</a>\r\n");
      out.write("        </span>\r\n");
      out.write("		<hr style=\"height: 1px; background-color: black;\">\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("	");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("        function goMain(){ \r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        function goProject(){ //프로젝트 둘러보기\r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function goProjectUp() { //프로젝트 올리기\r\n");
      out.write("			location.href = \"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function goCommunity(){ // 커뮤니티\r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function goConsumer(){ //고객지원\r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        function login(){ //로그인\r\n");
      out.write("        		 location.href=\"");
      out.print(request.getContextPath());
      out.write("/loginform.me\"\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function enroll(){//회원가입\r\n");
      out.write("        	  location.href=\"");
      out.print( request.getContextPath());
      out.write("/enrollForm.me\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	        <div id=\"body_content1\"> \r\n");
      out.write("	            <h1 id=\"title\">");
      out.print(project.getPrjTitle() );
      out.write("</h1>\r\n");
      out.write("	                <h3 id=\"category\">");
      out.print(projectCat.getPrjCatName());
      out.write("</h3>\r\n");
      out.write("	                <div id=\"top_content\">\r\n");
      out.write("	                    <div id=\"top_left_img\"><img src=\"resources/upfiles_project/");
      out.print(prjAttList.get(0).getChangeName());
      out.write("\" style=\"width: 725px; height: 418px;\"></div>\r\n");
      out.write("	                    <div id=\"top_right_bar\">\r\n");
      out.write("	                        <aside id=\"aside1\">\r\n");
      out.write("	                                <div><h4 style=\"margin-bottom: 10px; margin-top: 00px;\">모은금액</h4></div>\r\n");
      out.write("	                                <div style=\"margin-bottom: 20px\"><h1  class=\"textFiled\" style=\"display: inline;\">");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fgroupingUsed_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
        // /views/project_detail/projectDetailReview.jsp(31,114) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f0.setValue(project.getPrjCurrent());
        // /views/project_detail/projectDetailReview.jsp(31,114) name = groupingUsed type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f0.setGroupingUsed(true);
        int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fgroupingUsed_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
        _jspx_th_fmt_005fformatNumber_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
      }
      out.write("</h1>\r\n");
      out.write("	                                    <h4 style=\"display: inline;\">원</h4>\r\n");
      out.write("	                                        <span style=\"width: 100px;\"></span>\r\n");
      out.write("	                                    <span><h4 style=\"color: red; display: inline; float: right;\">");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
        // /views/project_detail/projectDetailReview.jsp(34,98) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f1.setValue((float)project.getPrjCurrent()/project.getPrjTarget());
        // /views/project_detail/projectDetailReview.jsp(34,98) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f1.setType("percent");
        int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
        _jspx_th_fmt_005fformatNumber_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
      }
      out.write(" 달성</h4></span></div>\r\n");
      out.write("	                                    <p style=\"clear: both;\"></p>\r\n");
      out.write("	                                <div style=\" margin-bottom: 10px;\"><h4 style=\"display: inline;\">펀딩시작일</h4></div>\r\n");
      out.write("	                                <div><h2  class=\"textFiled\">");
      //  fmt:formatDate
      org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
      boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
      try {
        _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatDate_005f0.setParent(null);
        // /views/project_detail/projectDetailReview.jsp(37,61) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f0.setValue(sdFormat.parse(project.getPrjStartDate()));
        // /views/project_detail/projectDetailReview.jsp(37,61) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f0.setType("date");
        // /views/project_detail/projectDetailReview.jsp(37,61) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f0.setPattern("MM월 dd일 ");
        int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
        if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
        _jspx_th_fmt_005fformatDate_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
      }
      out.write("</h2><span style=\"display: inline-flex;\">\r\n");
      out.write("	                                	");
 if((date.getTime()<sdFormat.parse(project.getPrjEndDate()).getTime())){
      out.write("\r\n");
      out.write("	                                		<h4>( ");
      out.print((sdFormat.parse(project.getPrjEndDate()).getTime()-(date.getTime()))/(24*60*60*1000));
      out.write(" 일 남음 )</h4></span></div> \r\n");
      out.write("	                               		");
}else{
      out.write("\r\n");
      out.write("	                                		<h4>( 마감된 프로젝트 )</h4></span></div> \r\n");
      out.write("	                               	");
}
      out.write("\r\n");
      out.write("	                                <div><h4 style=\"margin-bottom: 10px; margin-top: 0px;\">펀딩종료일</h4></div>\r\n");
      out.write("	                                <div><h2  class=\"textFiled\" >");
      //  fmt:formatDate
      org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
      boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
      try {
        _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatDate_005f1.setParent(null);
        // /views/project_detail/projectDetailReview.jsp(44,62) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f1.setValue(sdFormat.parse(project.getPrjEndDate()));
        // /views/project_detail/projectDetailReview.jsp(44,62) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f1.setType("date");
        // /views/project_detail/projectDetailReview.jsp(44,62) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f1.setPattern("MM월 dd일");
        int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
        if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
        _jspx_th_fmt_005fformatDate_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
      }
      out.write("</h2></div>\r\n");
      out.write("	                                <div style=\"margin-top: 30px; margin-bottom: 20px;\" id=\"buttonarea\">\r\n");
      out.write("	                                   ");
if(project.getStatus().equals("Y")){
      out.write("\r\n");
      out.write("	                                    <input type=\"button\" id=\"btn_fd\" value=\"펀딩하기\" onclick=\"goInfo();\"></input>\r\n");
      out.write("	                                   ");
}else{
      out.write("\r\n");
      out.write("	                                    <input type=\"button\" id=\"btn_fd2\" value=\"재펀딩요청하기 ");
      out.print(project.getPrjRecount());
      out.write("\"></input>\r\n");
      out.write("	                                    ");
}
      out.write("\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div>\r\n");
      out.write("	                                    <input type=\"button\" id=\"btn_po\" value=\"창작자 신고하기\" onclick=\"location.href=''\" ></input>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                            </aside>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("				<script type=\"text/javascript\">\r\n");
      out.write("	                $(document).on('click', \"#btn_fd2\", function(){\r\n");
      out.write("	        	            $.ajax({\r\n");
      out.write("	        	               url:\"countPlus.de\",\r\n");
      out.write("	        	               type:\"post\",\r\n");
      out.write("	        	               data:{num : ");
      out.print(num);
      out.write("},\r\n");
      out.write("	        	               success:function(status){\r\n");
      out.write("	        	            	   if(status==\"success\"){\r\n");
      out.write("	        	            		   selectList();\r\n");
      out.write("	        	            	   }\r\n");
      out.write("		        	            },\r\n");
      out.write("	        	               error:function(){\r\n");
      out.write("	        	                  console.log(\"ajax 통신 실패 - 댓글 등록\");\r\n");
      out.write("	        	               }\r\n");
      out.write("	        	            })\r\n");
      out.write("	        	         })\r\n");
      out.write("	        	      function selectList(){\r\n");
      out.write("	        	    	  ");
if(project.getStatus().equals("Y")){
      out.write("\r\n");
      out.write("                          <input type=\"button\" id=\"btn_fd\" value=\"펀딩하기\" onclick=\"checkLogin();\"></input>\r\n");
      out.write("                         ");
}else{
      out.write("\r\n");
      out.write("                         $(\"#buttonarea\").empty(); //기존 내용 지우고 다시 불러온다. \r\n");
      out.write("                          ");
}
      out.write("\r\n");
      out.write("	        	         $.ajax({\r\n");
      out.write("	        	            url:\"countSelect.de\",\r\n");
      out.write("	        	            data:{num : ");
      out.print(num);
      out.write('}');
      out.write(',');
      out.write(' ');
      out.write("\r\n");
      out.write("	        	            type:\"post\",\r\n");
      out.write("	        	            success:function(number){ \r\n");
      out.write("	        	               var value = \"\"\r\n");
      out.write("	        	            	   value='<input type=\"button\" id=\"btn_fd2\" value=\"재펀딩요청하기 '+number+'\"></input>';\r\n");
      out.write("	        	               	$(\"#buttonarea\").html(value);\r\n");
      out.write("	        	            },\r\n");
      out.write("	        	            error:function(){\r\n");
      out.write("	        	                console.log(\"ajax 통신 실패 - 댓글 조회\");\r\n");
      out.write("	        	             }\r\n");
      out.write("	        	          })\r\n");
      out.write("	        	       }\r\n");
      out.write("	                \r\n");
      out.write("	                </script>\r\n");
      out.write("	                <!---                         네비바 부분                   -->\r\n");
      out.write("	            <div id=\"navi_bar_parent\">\r\n");
      out.write("	                <div id=\"navi_bar\">\r\n");
      out.write("	                    <hr>\r\n");
      out.write("	                    <ul id=\"navi\">\r\n");
      out.write("	                        <li><a href=\"#;\" id=\"proInfo\" onclick=\"proInfoBtn()\">프로젝트 정보</a></li>\r\n");
      out.write("	                        <li><a href=\"#;\" id=\"proReview\" onclick=\"proReviewBtn()\">후기작성</a></li>\r\n");
      out.write("	                        <li><a href=\"#;\" id=\"proAsk\" onclick=\"proAskBtn()\">창작자에게 문의하기</a></li>\r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                    <hr style=\"clear: both;\">\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            \r\n");
      out.write("	            \r\n");
      out.write("	            <script>\r\n");
      out.write("				function goInfo(){\r\n");
      out.write("						alert(\"리워드를 선택해주세요\");\r\n");
      out.write("						location.href=\"");
      out.print(request.getContextPath());
      out.write("/proInfo.list?num=\"+");
      out.print(num);
      out.write(";\r\n");
      out.write("					\r\n");
      out.write("			    };\r\n");
      out.write("	            </script>\r\n");
      out.write("	  <div id=\"body_content2\">\r\n");
      out.write("        <div id=\"body\">\r\n");
      out.write("                <div id=\"box\">\r\n");
      out.write("                        <div id=\"creator\">\r\n");
      out.write("                        ");
if(at == null){ 
      out.write("\r\n");
      out.write("							<img id=\"rev_Img\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/default.PNG\"> \r\n");
      out.write("							");
} else { 
      out.write("\r\n");
      out.write("							<img id=\"rev_Img\"  src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/upfiles_profile/");
      out.print( at.getChangeName());
      out.write("\"> \r\n");
      out.write("							");
} 
      out.write("\r\n");
      out.write("                        ");
 if(loginUser != null){ 
      out.write("\r\n");
      out.write("                            <span id=\"name_area\"><h4 id=\"rev_Name\">");
      out.print(loginUser.getMemId() );
      out.write("</h4></span>\r\n");
      out.write("                            <textarea id=\"replyContent\" name=\"contentarea\" cols=\"107\" rows=\"8\" style=\"resize:none;\" placeholder=\"--자 이내로 입력해주세요.\"></textarea>\r\n");
      out.write("                        ");
 }else{ 
      out.write("\r\n");
      out.write("                        <span id=\"name_area\"><h4 id=\"rev_Name\">비회원</h4></span>\r\n");
      out.write("                        <textarea  id=\"replyContent\" name=\"contentarea\" readonly cols=\"107\" rows=\"8\" style=\"resize:none;\" placeholder=\"로그인한 사용자만 가능한 서비스입니다. 로그인 후 이용해주세요\"></textarea>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"button\" id=\"btn_con\" value=\"댓글작성\"></input><br><br><br><br>\r\n");
      out.write("                        <hr>\r\n");
      out.write("\r\n");
      out.write("                 <table id=\"reviewArea\">\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    body{\r\n");
      out.write("        min-width:1200px;\r\n");
      out.write("    }\r\n");
      out.write("    #footer{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:200px;\r\n");
      out.write("        background-color: lightgray;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-content{\r\n");
      out.write("        width:80%;\r\n");
      out.write("        height:200px;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("        padding-top:50px;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-1{\r\n");
      out.write("        font: 20px bolder;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-2{\r\n");
      out.write("        font: 5px bolder;\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("   \r\n");
      out.write("    <div id=\"footer-content\">\r\n");
      out.write("        <div id=\"footer-1\">\r\n");
      out.write("            skyline\r\n");
      out.write("        </div><br>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"footer-2\">\r\n");
      out.write("            <p id=\"p1\">\r\n");
      out.write("                <label style=\"color:gray;\">회사명</label> 국민체조  | <label style=\"color:gray;\">주소</label> 서울시 강남구 역삼동 KH\r\n");
      out.write("            </p>\r\n");
      out.write("            <p id=\"p2\">\r\n");
      out.write("                <label style=\"color:gray;\">대표번호</label> 02-0000-0000 | <label style=\"color:gray;\">운영시간</label> 9:00~18:00 (주말, 공휴일 제외)\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        $('#proReview').css('color','black');\r\n");
      out.write("        $('#proInfo').click(function() {\r\n");
      out.write("	    	location.href=\"");
      out.print(request.getContextPath());
      out.write("/proInfo.list?num=\"+");
      out.print(num);
      out.write(";\r\n");
      out.write("		});\r\n");
      out.write("	    $('#proReview').click(function() {\r\n");
      out.write("	    	location.href=\"");
      out.print(request.getContextPath());
      out.write("/proReview.list?num=\"+");
      out.print(num);
      out.write(";\r\n");
      out.write("		});\r\n");
      out.write("	    $('#proAsk').click(function() {\r\n");
      out.write("	    	location.href=\"");
      out.print(request.getContextPath());
      out.write("/proAsk.list?num=\"+");
      out.print(num);
      out.write(";\r\n");
      out.write("		});\r\n");
      out.write("	    </script>\r\n");
      out.write("	    <script type=\"text/javascript\">\r\n");
      out.write("	    $(function(){\r\n");
      out.write("	    	selectReviewList(); // 조회\r\n");
      out.write("	         $(\"#btn_con\").click(function(){ //댓글 등록\r\n");
      out.write("	            var content = $(\"#replyContent\").val();\r\n");
      out.write("	            var num = ");
      out.print(num);
      out.write(";\r\n");
      out.write("	            \r\n");
      out.write("	            $.ajax({\r\n");
      out.write("	               url:\"reinsert.de\",\r\n");
      out.write("	               type:\"post\",\r\n");
      out.write("	               data:{\r\n");
      out.write("	                  content:content, \r\n");
      out.write("	                  num:num\r\n");
      out.write("	               },\r\n");
      out.write("	               success:function(status){\r\n");
      out.write("	                  if(status == \"success\"){ //등록이 성공하면 조회되어야한다. \r\n");
      out.write("	                	  selectReviewList();\r\n");
      out.write("	                     $(\"#replyContent\").val(\"\");\r\n");
      out.write("	                  }\r\n");
      out.write("	               },\r\n");
      out.write("	               error:function(){\r\n");
      out.write("	                  console.log(\"ajax 통신 실패 - 댓글 등록\");\r\n");
      out.write("	               }\r\n");
      out.write("	            })\r\n");
      out.write("	         })\r\n");
      out.write("	      });   \r\n");
      out.write("	   \r\n");
      out.write("	      function selectReviewList(){\r\n");
      out.write("	    	  var id = $('.creatorName').attr(\"data_id\");\r\n");
      out.write("	         $(\"#reviewArea\").empty(); //기존 내용 지우고 다시 불러온다. \r\n");
      out.write("	         $.ajax({\r\n");
      out.write("	            url:\"relist.de\",\r\n");
      out.write("	            data:{num : ");
      out.print(num);
      out.write('}');
      out.write(',');
      out.write(' ');
      out.write("\r\n");
      out.write("	            type:\"get\",\r\n");
      out.write("	            success:function(list){ \r\n");
      out.write("	               var value = \"\"\r\n");
      out.write("	               for(var i in list){\r\n");
      out.write("	            	   if(list[i].changeName==null){\r\n");
      out.write("	            	   value += '<tr>'+\r\n");
      out.write("	            		   '<td style=\"width:70px\"><img class=\"imgContent\" src='+\"resources/images/default.PNG></td>\"+\r\n");
      out.write("	                      '<td><h4 class=\"creatorName\" data_id=\"'+list[i].memId+'\">'+list[i].memId+'</h4></td>'+\r\n");
      out.write("	                      '<td></td>'+\r\n");
      out.write("		                 '</tr>'+\r\n");
      out.write("		                 '<tr>'+\r\n");
      out.write("		                     '<td></td>'+\r\n");
      out.write("		                      '<td><p class=\"text_a\">'+list[i].reviewContent+'</p></td>'+\r\n");
      out.write("		                     '<td></td>'+\r\n");
      out.write("		                 '</tr>'+\r\n");
      out.write("		             	       '<td></td>'+\r\n");
      out.write("		             	       '<td></td>'+\r\n");
      out.write("		             	   '<td><div class=\"delete_btn\" data_No=\"'+list[i].reviewNo+'\">삭제</div></td>'+\r\n");
      out.write("		             	  '</tr>'+\r\n");
      out.write("		                  '<tr>'+\r\n");
      out.write("		                  '<td colspan=\"3\"><hr style=\"width:950px\"></td>'+\r\n");
      out.write("		                  '</tr>';\r\n");
      out.write("	               }else{\r\n");
      out.write("	            	   value += '<tr>'+\r\n");
      out.write("            		   '<td style=\"width:70px\"><img class=\"imgContent\" src='+\"resources/upfiles_profile/\"+list[i].changeName+'></td>'+\r\n");
      out.write("                      '<td><h4 class=\"creatorName\" data_id=\"'+list[i].memId+'\">'+list[i].memId+'</h4></td>'+\r\n");
      out.write("                      '<td></td>'+\r\n");
      out.write("	                 '</tr>'+\r\n");
      out.write("	                 '<tr>'+\r\n");
      out.write("	                     '<td></td>'+\r\n");
      out.write("	                      '<td><p class=\"text_a\">'+list[i].reviewContent+'</p></td>'+\r\n");
      out.write("	                     '<td></td>'+\r\n");
      out.write("	                 '</tr>'+\r\n");
      out.write("	             	       '<td></td>'+\r\n");
      out.write("	             	       '<td></td>'+\r\n");
      out.write("	             	   '<td><div class=\"delete_btn\" data_No=\"'+list[i].reviewNo+'\">삭제</div></td>'+\r\n");
      out.write("	             	  '</tr>'+\r\n");
      out.write("	                  '<tr>'+\r\n");
      out.write("	                  '<td colspan=\"3\"><hr style=\"width:950px\"></td>'+\r\n");
      out.write("	                  '</tr>';\r\n");
      out.write("	            	   \r\n");
      out.write("	               }\r\n");
      out.write("	               }\r\n");
      out.write("	               	$(\"#reviewArea\").html(value);\r\n");
      out.write("	            },\r\n");
      out.write("	            error:function(){\r\n");
      out.write("	                console.log(\"ajax 통신 실패 - 댓글 조회\");\r\n");
      out.write("	             }\r\n");
      out.write("	          })\r\n");
      out.write("	       }\r\n");
      out.write("	      \r\n");
      out.write("        </script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        \r\n");
      out.write("        $(document).on('click', '.delete_btn', function(){\r\n");
      out.write("         	var reNum = $(this).attr(\"data_No\"); \r\n");
      out.write("         	\r\n");
      out.write("	    	  console.log(reNum);\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                url : \"redelete.de\",\r\n");
      out.write("                data : {\r\n");
      out.write("              	  reNum : reNum,\r\n");
      out.write("              	  num : ");
      out.print(num);
      out.write("\r\n");
      out.write("                },\r\n");
      out.write("                type : \"post\",\r\n");
      out.write("                success : function(status){\r\n");
      out.write("                    if(status == \"success\"){ \r\n");
      out.write("                    	 selectReviewList();\r\n");
      out.write("                         alert(\"삭제 완료\");\r\n");
      out.write("                     } else {\r\n");
      out.write("                    	 alert(\"후기는 본인만 삭제 가능합니다.\");\r\n");
      out.write("                     }\r\n");
      out.write("                },\r\n");
      out.write("                error : function(status){\r\n");
      out.write("                	alert(\"삭제 실패\");\r\n");
      out.write("                }\r\n");
      out.write("			})\r\n");
      out.write("		});\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
