/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-25 14:04:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.project.model.vo.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import com.kh.member.model.vo.Member;
import com.kh.attachment.model.vo.ProfileAttachment;

public final class viewAllProject_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/project/../common/footer.jsp", Long.valueOf(1629160704073L));
    _jspx_dependants.put("/views/project/../common/menubar.jsp", Long.valueOf(1629435486986L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.kh.project.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.kh.attachment.model.vo.ProfileAttachment");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
	Date date = new Date();
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	
	Date startDate, endDate;
	
	ArrayList<Project> list = (ArrayList<Project>)request.getAttribute("list");
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	int allListCount = (int)request.getAttribute("allListCount");
	
	int listCount = pi.getListCount();
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("div, span, applet, object, iframes, h1, h2, h3, h4, h5, h6,\r\n");
      out.write("p, blockquote, pre, a, abbr, acronym, address, big, quotes, code, del,\r\n");
      out.write("dfn, em, img, ins, kbd, q, s, samp, small, strike, sub, sup, tt, var, u,\r\n");
      out.write("i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table,\r\n");
      out.write("caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas,\r\n");
      out.write("details, embed, figure, figcaption, footer, header, hgroup, menu, nav,\r\n");
      out.write("output, ruby, section, summary, time, mark, audio, video {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	border: 0;\r\n");
      out.write("	font-size: 100%;\r\n");
      out.write("	do: inherit;\r\n");
      out.write("	vertical-align: baseline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article, aside, details, figcaption, figure, hgroup,\r\n");
      out.write("menu, nav, section {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote, q {\r\n");
      out.write("	quotes: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote : before, blockquote : after, q : before, q : after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	content: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	border-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*css 초기화*/\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("	height: 400px;\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	order-radius: 15px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	margin-left: 30px;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-header {\r\n");
      out.write("	-webkit-transition: 0.5s; /*사파리 & 크롬*/\r\n");
      out.write("    -moz-transition: 0.5s;  /*파이어폭스*/\r\n");
      out.write("    -ms-transition: 0.5s;	/*인터넷 익스플로러*/\r\n");
      out.write("    -o-transition: 0.5s;  /*오페라*/\r\n");
      out.write("    transition: 0.5s;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 270px;\r\n");
      out.write("	border-radius: 15px 15px 0 0;\r\n");
      out.write("	background-image: url(\"images/korea.jpeg\");\r\n");
      out.write("	background-size: 100% 280px;\r\n");
      out.write("	background-repeat: no-repeat;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-header-is_closed{\r\n");
      out.write("    background-color: #EF5A31 ;\r\n");
      out.write("    color: #FFF ;\r\n");
      out.write("    font-weight: bold ;\r\n");
      out.write("    text-align: center ;\r\n");
      out.write("    float: right;\r\n");
      out.write("    margin: 15px 15px 0 0;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    padding: 10px 10px;\r\n");
      out.write("    line-height: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body-header{\r\n");
      out.write("	line-height: 25px;\r\n");
      out.write("	margin: 10px 20px 0px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body-hashtag {\r\n");
      out.write("	color: #2478FF;\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body-footer {\r\n");
      out.write("  	position: absolute; \r\n");
      out.write("  	margin-top: 15px;\r\n");
      out.write("  	margin-bottom: 6px;\r\n");
      out.write("    bottom: 0; \r\n");
      out.write("    width: 314px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #9FA5A8;\r\n");
      out.write("    padding: 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    margin-right: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-count_text {\r\n");
      out.write("    width: 25px;\r\n");
      out.write("    height: 17px;\r\n");
      out.write("	background: url(\"images/eye.jpg\") no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-count_view {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("	width: 25px;\r\n");
      out.write("    height: 17px;\r\n");
      out.write("	background: url(\"images/comment.jpg\") no-repeat;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".count_rate {\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".outer {\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");

 	Member loginUser = (Member)session.getAttribute("loginUser");
 	ProfileAttachment at = (ProfileAttachment)session.getAttribute("at");
 	String message = (String)session.getAttribute("msg");
 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Fund-ing</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script> \r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	min-width: 1200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navWrap {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 50px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navWrap>.nav {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navWrap>.logo {\r\n");
      out.write("	width: 700px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: rgb(31, 80, 126);\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	display: table-cell;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	font-family: 'Black Han Sans';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: 160px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	display: table-cell;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	font-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu:hover {\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: black 1px solid;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("	background-color: rgb(31, 80, 126);\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userInfo {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:visited {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("	color: rgb(31, 80, 126);;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("	border-radius: 70%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    var msg = \"");
      out.print(message);
      out.write("\";\r\n");
      out.write("    \r\n");
      out.write("    if(msg != \"null\"){\r\n");
      out.write("       alert(msg);	\r\n");
      out.write("       \r\n");
      out.write("       ");
session.removeAttribute("msg");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write(" 	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
 if(loginUser == null){ 
      out.write("\r\n");
      out.write("	<div class=\"navWrap\">\r\n");
      out.write("		<span class=\"nav\">\r\n");
      out.write("			<div class=\"logo\">fund-ing</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goMain();\">홈</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProject();\">프로젝트 둘러보기</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProjectUp();\">프로젝트 올리기</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goCommunity();\">커뮤니티</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goConsumer();\">고객지원</div>\r\n");
      out.write("\r\n");
      out.write("		</span> \r\n");
      out.write("		<span class=\"info\">\r\n");
      out.write("			<button class=\"btn\" onclick=\"login()\">로그인</button>&nbsp;\r\n");
      out.write("			<button class=\"btn\" onclick=\"enroll()\">회원가입</button>\r\n");
      out.write("		</span>\r\n");
      out.write("		<hr style=\"height: 1px; background-color: black;\">\r\n");
      out.write("	</div>\r\n");
      out.write("	");
 }else{
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		");
if(loginUser.getMemNo() == 100) { 
      out.write(" <!-- 관리자 로그인상태라면 -->\r\n");
      out.write("		<div class=\"navWrap\">\r\n");
      out.write("		<span class=\"nav\">\r\n");
      out.write("			<div class=\"logo\">fund-ing</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goMain();\">홈</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProject();\">프로젝트 둘러보기</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProjectUp();\">프로젝트 올리기</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goCommunity();\">커뮤니티</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goConsumer();\">고객지원</div>\r\n");
      out.write("\r\n");
      out.write("		</span> \r\n");
      out.write("		\r\n");
      out.write("		<img id=\"profile\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/default.PNG\" style=\"width:50px; height:50px\"> \r\n");
      out.write("		\r\n");
      out.write("		<span class=\"userInfo\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/memberList.bo\" style=\"font-size:15px; font-weight:bold;\">회원 리스트</a><br>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\" style=\"font-size:10px; font-weight:bold; color:red;\"> 로그아웃</a>\r\n");
      out.write("        </span>\r\n");
      out.write("		<hr style=\"height: 1px; background-color: black;\">\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		");
} else {
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"navWrap\">\r\n");
      out.write("		<span class=\"nav\">\r\n");
      out.write("			<div class=\"logo\">fund-ing</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goMain();\">홈</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProject();\">프로젝트 둘러보기</div>\r\n");
      out.write("			<div class=\"menu\" onclick=\"goProjectUp();\">프로젝트 올리기</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goCommunity();\">커뮤니티</div>\r\n");
      out.write("			<div class=\"menu\" style=\"width: 100px;\" onclick=\"goConsumer();\">고객지원</div>\r\n");
      out.write("\r\n");
      out.write("		</span> \r\n");
      out.write("		\r\n");
      out.write("		");
if(at == null){ 
      out.write("\r\n");
      out.write("		<img id=\"profile\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/default.PNG\" style=\"width:50px; height:50px\"> \r\n");
      out.write("		");
} else { 
      out.write("\r\n");
      out.write("		<img id=\"profile\"  src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/upfiles_profile/");
      out.print( at.getChangeName());
      out.write("\" style=\"width:50px; height:50px\"> \r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		 \r\n");
      out.write("		<span class=\"userInfo\">\r\n");
      out.write("            <a href=\"\" style=\"font-size:15px; font-weight:bold;\">");
      out.print( loginUser.getMemName() );
      out.write("</a><br>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\" style=\"font-size:10px; font-weight:bold; color:red;\"> 로그아웃</a>\r\n");
      out.write("        </span>\r\n");
      out.write("		<hr style=\"height: 1px; background-color: black;\">\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("	");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("        function goMain(){ \r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        function goProject(){ //프로젝트 둘러보기\r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function goProjectUp() { //프로젝트 올리기\r\n");
      out.write("			location.href = \"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function goCommunity(){ // 커뮤니티\r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function goConsumer(){ //고객지원\r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        function login(){ //로그인\r\n");
      out.write("        		 location.href=\"");
      out.print(request.getContextPath());
      out.write("/loginform.me\"\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function enroll(){//회원가입\r\n");
      out.write("        	  location.href=\"");
      out.print( request.getContextPath());
      out.write("/enrollForm.me\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("        <h1 style=\"margin-left:10px\">모든 프로젝트 둘러보기</h1>\r\n");
      out.write("        <h3 style=\"margin-left:10px\">");
      out.print( allListCount );
      out.write("개의 프로젝트가 있습니다.</h3>\r\n");
      out.write("		<hr>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"listArea\" align=\"center\">\r\n");
      out.write("			");
if(list.isEmpty()){ 
      out.write("\r\n");
      out.write("				<h3>조회된 리스트가 없습니다.</h3>\r\n");
      out.write("			");
}else{ 
      out.write("\r\n");
      out.write("				");
for(Project p : list){ 
      out.write("\r\n");
      out.write("		        <a href=\"#\"> <!-- 클릭 시 링크 설정 -->\r\n");
      out.write("		\r\n");
      out.write("		            <div class=\"card\">\r\n");
      out.write("		\r\n");
      out.write("		                <!-- 카드 헤더 -->\r\n");
      out.write("		                <div class=\"card-header\">\r\n");
      out.write("		                    <div class=\"card-header-is_closed\"> \r\n");
      out.write("		                        <div class=\"card-header-text\">남은 기간 </div>\r\n");
      out.write("		                        ");

			                        startDate = sdf.parse(p.getPrjStartDate());
		                        	endDate = sdf.parse(p.getPrjEndDate());
		                        
      out.write("\r\n");
      out.write("		                        <div class=\"card-header-number\">");
      out.print( (endDate.getTime() - startDate.getTime()) / (24*60*60*1000) );
      out.write("일 </div> \r\n");
      out.write("		                    </div >\r\n");
      out.write("		                </div>\r\n");
      out.write("		\r\n");
      out.write("		                <!--  카드 바디 -->\r\n");
      out.write("		                <div class=\"card-body\">\r\n");
      out.write("		\r\n");
      out.write("		                    <!--  카드 바디 헤더 -->\r\n");
      out.write("		                    <div class=\"card-body-header\">\r\n");
      out.write("		                        <h1>");
      out.print( p.getPrjTitle() );
      out.write("</h1>\r\n");
      out.write("		                        <p class=\"card-body-hashtag\">#");
      out.print( p.getPrjCatName() );
      out.write("</p>\r\n");
      out.write("		                        <p class = \"card-body-nickname\">");
      out.print( p.getCreName() );
      out.write("</p>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		\r\n");
      out.write("		                    <!--  카드 바디 본문 -->\r\n");
      out.write("		\r\n");
      out.write("		                    <!--  카드 바디 푸터 -->\r\n");
      out.write("		                    <div class=\"card-body-footer\">\r\n");
      out.write("		                        <hr style=\"margin-bottom: 8px; opacity: 0.5; border-color: #EF5A31\">\r\n");
      out.write("		                        <i class=\"icon icon-count_text\"></i>모인 금액\r\n");
      out.write("		                        <i class=\"icon icon-count_view\"></i>");
      out.print( p.getPrjCurrent() );
      out.write("원\r\n");
      out.write("		                        <i class=\"count_rate\">");
      out.print( p.getPrjCurrent() / p.getPrjTarget() * 100 );
      out.write("% </i>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		\r\n");
      out.write("		                </div>\r\n");
      out.write("		\r\n");
      out.write("		            </div>\r\n");
      out.write("		\r\n");
      out.write("		        </a>\r\n");
      out.write("		        ");
} 
      out.write("\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("	    </div>\r\n");
      out.write("	    \r\n");
      out.write("	    <br><br>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 페이징바 만들기 -->\r\n");
      out.write("		<div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("			<!-- 맨 처음으로 (<<) -->\r\n");
      out.write("			<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/viewAll.pr?currentPage=1'\"> &lt;&lt; </button>\r\n");
      out.write("		\r\n");
      out.write("			<!-- 이전페이지로(<) -->\r\n");
      out.write("			");
if(currentPage == 1){ 
      out.write("\r\n");
      out.write("			<button disabled> &lt; </button>\r\n");
      out.write("			");
}else{ 
      out.write("\r\n");
      out.write("			<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/viewAll.pr?currentPage=");
      out.print( currentPage-1 );
      out.write("'\"> &lt; </button>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<!-- 페이지 목록 -->\r\n");
      out.write("			");
for(int p=startPage; p<=endPage; p++){ 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				");
if(p == currentPage){ 
      out.write("\r\n");
      out.write("				<button disabled> ");
      out.print( p );
      out.write(" </button>\r\n");
      out.write("				");
}else{ 
      out.write("\r\n");
      out.write("				<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/viewAll.pr?currentPage=");
      out.print( p );
      out.write("'\"> ");
      out.print( p );
      out.write(" </button>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<!-- 다음페이지로(>) -->\r\n");
      out.write("			");
if(currentPage == maxPage){ 
      out.write("\r\n");
      out.write("			<button disabled> &gt; </button>\r\n");
      out.write("			");
}else { 
      out.write("\r\n");
      out.write("			<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/viewAll.pr?currentPage=");
      out.print( currentPage+1 );
      out.write("'\"> &gt; </button>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<!-- 맨 끝으로 (>>) -->\r\n");
      out.write("			<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/viewAll.pr?currentPage=");
      out.print(maxPage);
      out.write("'\"> &gt;&gt; </button>\r\n");
      out.write("		</div> \r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<br><br>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    body{\r\n");
      out.write("        min-width:1200px;\r\n");
      out.write("    }\r\n");
      out.write("    #footer{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:200px;\r\n");
      out.write("        background-color: lightgray;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-content{\r\n");
      out.write("        width:80%;\r\n");
      out.write("        height:200px;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("        padding-top:50px;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-1{\r\n");
      out.write("        font: 20px bolder;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-2{\r\n");
      out.write("        font: 5px bolder;\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("   \r\n");
      out.write("    <div id=\"footer-content\">\r\n");
      out.write("        <div id=\"footer-1\">\r\n");
      out.write("            skyline\r\n");
      out.write("        </div><br>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"footer-2\">\r\n");
      out.write("            <p id=\"p1\">\r\n");
      out.write("                <label style=\"color:gray;\">회사명</label> 국민체조  | <label style=\"color:gray;\">주소</label> 서울시 강남구 역삼동 KH\r\n");
      out.write("            </p>\r\n");
      out.write("            <p id=\"p2\">\r\n");
      out.write("                <label style=\"color:gray;\">대표번호</label> 02-0000-0000 | <label style=\"color:gray;\">운영시간</label> 9:00~18:00 (주말, 공휴일 제외)\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
